[tool.poetry]
name = "adventofcode2023"
version = "0.1.0"
description = ""
authors = ["Uy Nguyen"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
